import questions.*

fun main(args: Array<String>) {
//    Question_1_Two_Sum.runQuestion1()
//    Question_2_Add_Two_Numbers.runQuestion2()
//    Question_3_Longest_Substring_Without_Repeating_Characters.runQuestion3()
//    Question_4_Median_of_Two_Sorted_Arrays.runQuestion4()
//    Question_5_Longest_Palindromic_Substring.runQuestion5()
//    Question_6_Zig_Zag_Conversion.runQuestion6()
//    Question_8_String_to_Integer.runQuestion8()
//    Question_9_Palindrome_Number.runQuestion9()
//    Question_11_Container_With_Most_Water.runQuestion11()
//    Question_12_Integer_to_Roman.runQuestion12()
//    Question_13_Roman_to_Integer.runQuestion13()
//    Question_14_Longest_Common_Prefix.runQuestion14()
//    Question_15_3Sum.runQuestion15()
//    Question_16_3Sum_Closest.runQuestion16()
//    Question_17_Letter_Combinations_of_a_Phone_Number.runQuestion17()
//    Question_19_Remove_Nth_Node_From_End_of_List.runQuestion19()
//    Question_22_Generate_Parentheses.runQuestion22()
//    Question_23_Merge_k_Sorted_Lists.runQuestion23()
//    Question_29_Divide_Two_Integers.runQuestion29()
//    Question_43_Multiply_Strings.runQuestion43()
//    Question_46_Permutations.runQuestion46()
//    Question_283_Move_Zeroes.runQuestion283()
//    Question_287_Find_the_Duplicate_Number.runQuestion287()
//    Question_442_Find_All_Duplicates_in_an_Array.runQuestion442()
//    Question_576_Out_of_Boundary_Paths.runQuestion576()
//    Question_652_Find_Duplicate_Subtrees.runQuestion652()
//    Question_781_Rabbits_in_Forest.runQuestion781()
//    Question_948_Bag_of_Tokens.runQuestion948()
//    Question_991_Broken_Calculator.runQuestion991()
//    Question_1054_Distant_Barcodes.runQuestion1054()
//    Question_1301_Number_of_Paths_with_Max_Score.runQuestion1301()
//    Question_1346_Check_If_N_and_Its_Double_Exist.runQuestion1346()
    Question_1705_Maximum_Number_of_Eaten_Apples.runQuestion1705()
//    Question_1882_Process_Tasks_Using_Servers.runQuestion1882()
//    Question_2032_Two_Out_of_Three.runQuestion2032()
//    Question_2057_Smallest_Index_With_Equal_Value.runQuestion2057()
//    Question_2126_Destroying_Asteroids.runQuestion2126()
//    Question_2216_Minimum_Deletions_to_Make_Array_Beautiful.runQuestion2216()
}